Fix build error with clang
At least in some configurations of clang, `-Wreturn-type` is set to
error by default, causing the magic build to fail with:

```
ExtCell.c:115:2: error: non-void function 'ExtCell' should return a value [-Wreturn-type]
```